linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - errchkjson
    - errname
    - errorlint
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godox
    - goheader
    - gosec
    - gosmopolitan
    - iface
    - inamedparam
    - ireturn
    - maintidx
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - sloglint
    - sqlclosecheck
    - usestdlibvars
  exclusions:
    paths:
      - ".*_test\\.go$"
      - "main.go"
      - ".*gen.*"
      
run:
  relative-path-mode: gomod



output:
  sort-results: true
  sort-order:
    - linter
    - severity
    - file