services:
  backend:
    build: .
    container_name: avito-pickup-point
    ports:
      - "8080:8080"
    environment:
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: 1234
        DATABASE_NAME: postgres
        DATABASE_HOST: db
        SERVER_PORT: 8080
        JWT_SECRET: secret
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql